### ISSUE TITLE
Incompatible with python-Levenshtein >=0.20

### ISSUE THREAD

**Issue by ziddey** [seatgeek/thefuzz#35]
```
>>> process.extractOne('abc', ['abc', 'def', 'ghi'])
Traceback (most recent call last):
  File "/home/ziddey/projects/biyombo/venv_biyombo/lib/python3.10/site-packages/thefuzz/process.py", line 108, in extractWithoutOrder
    for key, choice in choices.items():
AttributeError: 'list' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ziddey/projects/biyombo/venv_biyombo/lib/python3.10/site-packages/thefuzz/process.py", line 168, in extract
    return heapq.nlargest(limit, sl, key=lambda i: i[1]) if limit is not None else \
  File "/usr/lib/python3.10/heapq.py", line 563, in nlargest
    result = [(key(elem), i, elem) for i, elem in zip(range(0, -n, -1), it)]
  File "/usr/lib/python3.10/heapq.py", line 563, in <listcomp>
    result = [(key(elem), i, elem) for i, elem in zip(range(0, -n, -1), it)]
  File "/home/ziddey/projects/biyombo/venv_biyombo/lib/python3.10/site-packages/thefuzz/process.py", line 117, in extractWithoutOrder
    score = scorer(processed_query, processed)
  File "/home/ziddey/projects/biyombo/venv_biyombo/lib/python3.10/site-packages/thefuzz/fuzz.py", line 276, in WRatio
    base = ratio(p1, p2)
  File "/home/ziddey/projects/biyombo/venv_biyombo/lib/python3.10/site-packages/thefuzz/utils.py", line 38, in decorator
    return func(*args, **kwargs)
  File "/home/ziddey/projects/biyombo/venv_biyombo/lib/python3.10/site-packages/thefuzz/utils.py", line 29, in decorator
    return func(*args, **kwargs)
  File "/home/ziddey/projects/biyombo/venv_biyombo/lib/python3.10/site-packages/thefuzz/utils.py", line 47, in decorator
    return func(*args, **kwargs)
  File "/home/ziddey/projects/biyombo/venv_biyombo/lib/python3.10/site-packages/thefuzz/fuzz.py", line 28, in ratio
    return utils.intr(100 * m.ratio())
  File "/home/ziddey/projects/biyombo/venv_biyombo/lib/python3.10/site-packages/thefuzz/StringMatcher.py", line 64, in ratio
    self._ratio = ratio(self._str1, self._str2)
NameError: name 'ratio' is not defined
```

python-Levenshtein is now a metapackage, installing Levenshtein

https://github.com/maxbachmann/Levenshtein/blob/main/src/Levenshtein/__init__.py

**Comment by ziddey** [comment]
Disregard. Seems the upgrade failed to properly install Levenshtein.

#34 may be related?

**Comment by aodin** [comment]
I encountered the original `NameError` when updating an existing install (specifically poetry updated  `python-levenshtein` from `0.12.2` to `0.20.5`). Uninstalling and re-installing all related packages fixed the issue:

```
pip uninstall Levenshtein python-Levenshtein rapidfuzz thefuzz
pip install -U "thefuzz[speedup]"
```

**Comment by maxbachmann** [comment]
The reason for the issue appears to be that historically the package was named `python-Levenshtein` but installed as `Levenshtein`, which was always kind of messed up.
Now in the newer releases this is somewhat resolved by having a separate package called `Levenshtein` and `python-Levenshtein` just installing this package. I hoped pip would be able to figure this out when upgrading the package, but apparently it fails to do so (not sure whether that's a bug, or something like this is just not intended). Sorry for the unexpected breakage.

As you noted uninstalling `python-Levenshtein` and simply installing it again should fix the issue.
