### ISSUE TITLE
BUG: Can't handle `nan`

### ISSUE THREAD

**Issue by Zeroto521** [seatgeek/thefuzz#41]
Problem:

`nan` value is not None, so it will be skipped by `check_for_none`.
And `nan` is float and don't have `len` method, so `check_empty_string` raises an error.

```python
>>> from thefuzz.fuzz import ratio
>>> ratio("a", float("nan"))  # or `np.nan`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Zero\mambaforge\envs\dtoolkit-dev\lib\site-packages\thefuzz\utils.py", line 38, in decorator
    return func(*args, **kwargs)
  File "C:\Users\Zero\mambaforge\envs\dtoolkit-dev\lib\site-packages\thefuzz\utils.py", line 29, in decorator
    return func(*args, **kwargs)
  File "C:\Users\Zero\mambaforge\envs\dtoolkit-dev\lib\site-packages\thefuzz\utils.py", line 46, in decorator
    if len(args[0]) == 0 or len(args[1]) == 0:
TypeError: object of type 'float' has no len()
```

Solution:

`check_for_none` need to be updated.
or create a new decorator for handling `nan` value.

https://github.com/seatgeek/thefuzz/blob/6e68af84e086b3e5f7253d4f9b0d6c7313e34637/thefuzz/utils.py#L33-L39

**Comment by maxbachmann** [comment]
Now that rapidfuzz is used under the hood, this is working

**Comment by maxbachmann** [comment]
@johnthedebs this is already fixed
